# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'dondecomo' do
  pod 'RNVectorIcons', :path => 'node_modules/react-native-vector-icons'
end

target 'dondecomoTests' do

end

